### ISSUE TITLE
error

### ISSUE THREAD

**Issue by moling-4435** [AlphaBrock/91porn#1]
[Errno 2] No such file or directory: 'I:\\91porn-master\\log\\sqlite.log'

**Comment by AlphaBrock** [comment]
you just need to create a directory which name log under the 91porn-master directory

**Comment by moling-4435** [comment]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='91porn.com', port=443): Max retries exceeded with url: /v.php?next=watch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F22015BEE0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

**Comment by AlphaBrock** [comment]
You need a Socks5 proxy or other to visit 91porn official website. If not, please use other domains that are not blocked.
