### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by DoomZoe** [AlphaBrock/91porn#2]
下载下来的都是.m3u8，然后报错
[2021-08-17 21:17:37,217] [WARNING] [downloader.py:downloader.m3u8s:81] [21328]
url:https://fdc.91p49.com/m3u8/509428/509428.m3u8, 下载失败, 返回状态码结果:400,
 返回结果:<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

, 重试次数:3

**Comment by AlphaBrock** [comment]
> 下载下来的都是.m3u8，然后报错
> [2021-08-17 21:17:37,217] [WARNING] [downloader.py:downloader.m3u8s:81] [21328]
> url:https://fdc.91p49.com/m3u8/509428/509428.m3u8, 下载失败, 返回状态码结果:400,
> 返回结果:
> 
> <title>400 Bad Request</title>
> # 400 Bad Request
> nginx , 重试次数:3

下载太频繁会有一定几率被屏蔽，下载回来的m3u8文件不是重点，脚本只是用来解析里面的地址，下载其中的短视频，然后上传到github中，最后转换成cdn连接存入sqlite数据库中
